### ISSUE TITLE
Loading results in over one thousand HTTP requests

### ISSUE THREAD

**Issue by denver-s** [claudebarde/my-tezos-defi#10]
Is this expected because it checks every single token?

![image](https://user-images.githubusercontent.com/31325316/125156000-7c65f280-e163-11eb-823f-e8a33261cfd1.png)

**Comment by claudebarde** [comment]
MyTezosDefi makes a lot of HTTP requests, not only to token contracts but also to different dexes and pools. The requests include fetching general data from contracts, getting users' balances, getting exchange rates from QuipuSwap, etc. There are also regular requests happening every minute and in some cases, these requests can be delayed and fire at the same time as the next ones. MTD tries to rely on indexers as little as possible to avoid overloading their APIs and uses Taquito extensively instead to fetch the required data, which also creates more requests client-side.
I am making some improvements at the moment to cache some results that don't need to be updated so often and to switch the dapp to a "selection-first" style where the users will select the tokens/pools/farms they are interested in and will only receive updates about them, thus reducing the number of HTTP requests.

**Comment by claudebarde** [comment]
I am switching MTD from using the QuipuSwap SDK to the TezTools API, which will considerably reduce the number of HTTP requests. The first tests show 200 requests on load, so that shouldn't be a problem anymore. I am closing the issue, for now, let me know if you experience the same issue when version 3 is out there.
